sudo: required
services: 
  - docker


before_install:
  - docker build -f dockerfile.dev -t veera0514/veerarepo:docker-react .

script:
  - docker run -e CI=true veera0514/veerarepo:docker-react  npm run test
